### ISSUE TITLE
1. Refactoring

### ISSUE THREAD

**Issue by Virtuoz1983** [Virtuoz1983/PVToto#1]
- Create scripts for every database objects according with our name conventions. (example - script for dbo.Numbers)
- Change database objects with these new changes

**Comment by PavloY** [comment]
Done

**Comment by Virtuoz1983** [comment]
On code review stage

**Comment by PavloY** [comment]
I agree

**Comment by Virtuoz1983** [comment]
Good job Pavlo. Issue resolved.
