### ISSUE TITLE
2. Remove physical "var" tables

### ISSUE THREAD

**Issue by Virtuoz1983** [Virtuoz1983/PVToto#2]
- change process flow for TOTO packet generation. (use temporary tables instead of physical database objects)
- add ability to choose count of var tables (with input variables)

**Comment by PavloY** [comment]
how we will build the job?
I make changes to the base, then keep the bak-files and put in a repository?

**Comment by Virtuoz1983** [comment]
No, lets do this without BU file. Let's modify scritps and load them into the repository. After this, I can take these files and make all necessary changes on my own database. 
So, after this we will be on the same page.

**Comment by PavloY** [comment]
ok, bro

**Comment by PavloY** [comment]
I changed in dbo.Tot_RecreateAllVarTables.sql
left to change dbo.Tot_InsertKuponsbyTirag.sql

**Comment by PavloY** [comment]
Added work with temporary tables in dbo.Tot_InsertKuponsbyTirag.sql

**Comment by Virtuoz1983** [comment]
Well done, but I have changed type of using temporary tables to the global.
